version: "3.3"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  ssr-front:
    ports:
      - ${FRONT_SSR_PORT}:3000
    build:
      context: ../shopcrm-front
      dockerfile: Dockerfile
    volumes:
      - ../shopcrm-front:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env
  mariadb:
      build:
        context: ./mariadb
        args:
          - http_proxy
          - https_proxy
          - no_proxy
          - MARIADB_VERSION=${MARIADB_VERSION}
      volumes:
        - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      ports:
        - "${MARIADB_PORT}:3306"
      environment:
        - TZ=${WORKSPACE_TIMEZONE}
        - MYSQL_DATABASE=${MARIADB_DATABASE}
        - MYSQL_USER=${MARIADB_USER}
        - MYSQL_PASSWORD=${MARIADB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      networks:
        - backend
  api-dev:
      image: nestjs-api-dev:1.0.0
      build:
          context: ../shopcrm-back
          target: development
      command: npm run start:debug
      ports:
          - 3000:3000
          - 9229:9229
      networks:
          - backend
      volumes:
          - ../shopcrm-back:/usr/src/app
          - /usr/src/app/node_modules
      restart: unless-stopped
  api-prod:
        image: nestjs-api-prod:1.0.0
        build:
            context: ../shopcrm-back
            target: production
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - backend
        volumes:
            - ../shopcrm-back:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped